version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"

  spring-boot-app:
    image: gyotro/url-shortener:1.0.8
    container_name: shorty
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
    ports:
      - "8080:8080"