apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: url-shortener
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  host: sh.xxxxx.kyma.ondemand.com
  service:
    name: url-shortener
    port: 8080
  rules:
    - path: /.*
      accessStrategies:
        - handler: allow
          config: {}
      methods: ["GET", "POST"]